/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProvisioningRouteImport } from './routes/provisioning'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoggedOutRouteImport } from './routes/logged-out'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SetupMfaRouteImport } from './routes/setup/mfa'
import { Route as Setup2faRouteImport } from './routes/setup/2fa'
import { Route as PasswordSetRouteImport } from './routes/password/set'
import { Route as PasswordForgotRouteImport } from './routes/password/forgot'
import { Route as AppScribeRouteImport } from './routes/app/scribe'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppAccountRouteImport } from './routes/app/account'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminBillingRouteImport } from './routes/admin/billing'
import { Route as LocaleSignupRouteImport } from './routes/$locale/signup'
import { Route as AppTranscribeIndexRouteImport } from './routes/app/transcribe/index'
import { Route as AppKnowledgeIndexRouteImport } from './routes/app/knowledge/index'
import { Route as AppFocusIndexRouteImport } from './routes/app/focus/index'
import { Route as AppDocsIndexRouteImport } from './routes/app/docs/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AppTranscribeAddRouteImport } from './routes/app/transcribe/add'
import { Route as AppMeetingsStartRouteImport } from './routes/app/meetings/start'
import { Route as AppMeetingsMeetingIdRouteImport } from './routes/app/meetings/$meetingId'
import { Route as AppFocusNewRouteImport } from './routes/app/focus/new'
import { Route as AppFocusNotebookIdRouteImport } from './routes/app/focus/$notebookId'
import { Route as AppDocsNewRouteImport } from './routes/app/docs/new'
import { Route as AppDocsKbSlugRouteImport } from './routes/app/docs/$kbSlug'
import { Route as AdminUsersInviteRouteImport } from './routes/admin/users/invite'
import { Route as LocalePasswordForgotRouteImport } from './routes/$locale/password/forgot'
import { Route as AppFocusNotebookIdEditRouteImport } from './routes/app/focus/$notebookId_.edit'
import { Route as AppFocusNotebookIdAddSourceRouteImport } from './routes/app/focus/$notebookId_.add-source'
import { Route as AppDocsKbSlugEditRouteImport } from './routes/app/docs/$kbSlug_.edit'
import { Route as AdminUsersUserIdEditRouteImport } from './routes/admin/users/$userId/edit'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvisioningRoute = ProvisioningRouteImport.update({
  id: '/provisioning',
  path: '/provisioning',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggedOutRoute = LoggedOutRouteImport.update({
  id: '/logged-out',
  path: '/logged-out',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SetupMfaRoute = SetupMfaRouteImport.update({
  id: '/setup/mfa',
  path: '/setup/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const Setup2faRoute = Setup2faRouteImport.update({
  id: '/setup/2fa',
  path: '/setup/2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordSetRoute = PasswordSetRouteImport.update({
  id: '/password/set',
  path: '/password/set',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordForgotRoute = PasswordForgotRouteImport.update({
  id: '/password/forgot',
  path: '/password/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScribeRoute = AppScribeRouteImport.update({
  id: '/scribe',
  path: '/scribe',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LocaleSignupRoute = LocaleSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const AppTranscribeIndexRoute = AppTranscribeIndexRouteImport.update({
  id: '/transcribe/',
  path: '/transcribe/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKnowledgeIndexRoute = AppKnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFocusIndexRoute = AppFocusIndexRouteImport.update({
  id: '/focus/',
  path: '/focus/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocsIndexRoute = AppDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppTranscribeAddRoute = AppTranscribeAddRouteImport.update({
  id: '/transcribe/add',
  path: '/transcribe/add',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMeetingsStartRoute = AppMeetingsStartRouteImport.update({
  id: '/meetings/start',
  path: '/meetings/start',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMeetingsMeetingIdRoute = AppMeetingsMeetingIdRouteImport.update({
  id: '/meetings/$meetingId',
  path: '/meetings/$meetingId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFocusNewRoute = AppFocusNewRouteImport.update({
  id: '/focus/new',
  path: '/focus/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFocusNotebookIdRoute = AppFocusNotebookIdRouteImport.update({
  id: '/focus/$notebookId',
  path: '/focus/$notebookId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocsNewRoute = AppDocsNewRouteImport.update({
  id: '/docs/new',
  path: '/docs/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocsKbSlugRoute = AppDocsKbSlugRouteImport.update({
  id: '/docs/$kbSlug',
  path: '/docs/$kbSlug',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminUsersInviteRoute = AdminUsersInviteRouteImport.update({
  id: '/users/invite',
  path: '/users/invite',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LocalePasswordForgotRoute = LocalePasswordForgotRouteImport.update({
  id: '/password/forgot',
  path: '/password/forgot',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const AppFocusNotebookIdEditRoute = AppFocusNotebookIdEditRouteImport.update({
  id: '/focus/$notebookId_/edit',
  path: '/focus/$notebookId/edit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFocusNotebookIdAddSourceRoute =
  AppFocusNotebookIdAddSourceRouteImport.update({
    id: '/focus/$notebookId_/add-source',
    path: '/focus/$notebookId/add-source',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDocsKbSlugEditRoute = AppDocsKbSlugEditRouteImport.update({
  id: '/docs/$kbSlug_/edit',
  path: '/docs/$kbSlug/edit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminUsersUserIdEditRoute = AdminUsersUserIdEditRouteImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/logged-out': typeof LoggedOutRoute
  '/login': typeof LoginRoute
  '/provisioning': typeof ProvisioningRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/$locale/signup': typeof LocaleSignupRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/app/account': typeof AppAccountRoute
  '/app/chat': typeof AppChatRoute
  '/app/scribe': typeof AppScribeRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/set': typeof PasswordSetRoute
  '/setup/2fa': typeof Setup2faRoute
  '/setup/mfa': typeof SetupMfaRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/$locale/password/forgot': typeof LocalePasswordForgotRoute
  '/admin/users/invite': typeof AdminUsersInviteRoute
  '/app/docs/$kbSlug': typeof AppDocsKbSlugRoute
  '/app/docs/new': typeof AppDocsNewRoute
  '/app/focus/$notebookId': typeof AppFocusNotebookIdRoute
  '/app/focus/new': typeof AppFocusNewRoute
  '/app/meetings/$meetingId': typeof AppMeetingsMeetingIdRoute
  '/app/meetings/start': typeof AppMeetingsStartRoute
  '/app/transcribe/add': typeof AppTranscribeAddRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/app/docs/': typeof AppDocsIndexRoute
  '/app/focus/': typeof AppFocusIndexRoute
  '/app/knowledge/': typeof AppKnowledgeIndexRoute
  '/app/transcribe/': typeof AppTranscribeIndexRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/app/docs/$kbSlug/edit': typeof AppDocsKbSlugEditRoute
  '/app/focus/$notebookId/add-source': typeof AppFocusNotebookIdAddSourceRoute
  '/app/focus/$notebookId/edit': typeof AppFocusNotebookIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/logged-out': typeof LoggedOutRoute
  '/login': typeof LoginRoute
  '/provisioning': typeof ProvisioningRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/$locale/signup': typeof LocaleSignupRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/app/account': typeof AppAccountRoute
  '/app/chat': typeof AppChatRoute
  '/app/scribe': typeof AppScribeRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/set': typeof PasswordSetRoute
  '/setup/2fa': typeof Setup2faRoute
  '/setup/mfa': typeof SetupMfaRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/$locale/password/forgot': typeof LocalePasswordForgotRoute
  '/admin/users/invite': typeof AdminUsersInviteRoute
  '/app/docs/$kbSlug': typeof AppDocsKbSlugRoute
  '/app/docs/new': typeof AppDocsNewRoute
  '/app/focus/$notebookId': typeof AppFocusNotebookIdRoute
  '/app/focus/new': typeof AppFocusNewRoute
  '/app/meetings/$meetingId': typeof AppMeetingsMeetingIdRoute
  '/app/meetings/start': typeof AppMeetingsStartRoute
  '/app/transcribe/add': typeof AppTranscribeAddRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/app/docs': typeof AppDocsIndexRoute
  '/app/focus': typeof AppFocusIndexRoute
  '/app/knowledge': typeof AppKnowledgeIndexRoute
  '/app/transcribe': typeof AppTranscribeIndexRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/app/docs/$kbSlug/edit': typeof AppDocsKbSlugEditRoute
  '/app/focus/$notebookId/add-source': typeof AppFocusNotebookIdAddSourceRoute
  '/app/focus/$notebookId/edit': typeof AppFocusNotebookIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/logged-out': typeof LoggedOutRoute
  '/login': typeof LoginRoute
  '/provisioning': typeof ProvisioningRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/$locale/signup': typeof LocaleSignupRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/app/account': typeof AppAccountRoute
  '/app/chat': typeof AppChatRoute
  '/app/scribe': typeof AppScribeRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/set': typeof PasswordSetRoute
  '/setup/2fa': typeof Setup2faRoute
  '/setup/mfa': typeof SetupMfaRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/$locale/password/forgot': typeof LocalePasswordForgotRoute
  '/admin/users/invite': typeof AdminUsersInviteRoute
  '/app/docs/$kbSlug': typeof AppDocsKbSlugRoute
  '/app/docs/new': typeof AppDocsNewRoute
  '/app/focus/$notebookId': typeof AppFocusNotebookIdRoute
  '/app/focus/new': typeof AppFocusNewRoute
  '/app/meetings/$meetingId': typeof AppMeetingsMeetingIdRoute
  '/app/meetings/start': typeof AppMeetingsStartRoute
  '/app/transcribe/add': typeof AppTranscribeAddRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/app/docs/': typeof AppDocsIndexRoute
  '/app/focus/': typeof AppFocusIndexRoute
  '/app/knowledge/': typeof AppKnowledgeIndexRoute
  '/app/transcribe/': typeof AppTranscribeIndexRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/app/docs/$kbSlug_/edit': typeof AppDocsKbSlugEditRoute
  '/app/focus/$notebookId_/add-source': typeof AppFocusNotebookIdAddSourceRoute
  '/app/focus/$notebookId_/edit': typeof AppFocusNotebookIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/admin'
    | '/app'
    | '/callback'
    | '/logged-out'
    | '/login'
    | '/provisioning'
    | '/signup'
    | '/verify'
    | '/$locale/signup'
    | '/admin/billing'
    | '/admin/settings'
    | '/app/account'
    | '/app/chat'
    | '/app/scribe'
    | '/password/forgot'
    | '/password/set'
    | '/setup/2fa'
    | '/setup/mfa'
    | '/admin/'
    | '/app/'
    | '/$locale/password/forgot'
    | '/admin/users/invite'
    | '/app/docs/$kbSlug'
    | '/app/docs/new'
    | '/app/focus/$notebookId'
    | '/app/focus/new'
    | '/app/meetings/$meetingId'
    | '/app/meetings/start'
    | '/app/transcribe/add'
    | '/admin/users/'
    | '/app/docs/'
    | '/app/focus/'
    | '/app/knowledge/'
    | '/app/transcribe/'
    | '/admin/users/$userId/edit'
    | '/app/docs/$kbSlug/edit'
    | '/app/focus/$notebookId/add-source'
    | '/app/focus/$notebookId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/callback'
    | '/logged-out'
    | '/login'
    | '/provisioning'
    | '/signup'
    | '/verify'
    | '/$locale/signup'
    | '/admin/billing'
    | '/admin/settings'
    | '/app/account'
    | '/app/chat'
    | '/app/scribe'
    | '/password/forgot'
    | '/password/set'
    | '/setup/2fa'
    | '/setup/mfa'
    | '/admin'
    | '/app'
    | '/$locale/password/forgot'
    | '/admin/users/invite'
    | '/app/docs/$kbSlug'
    | '/app/docs/new'
    | '/app/focus/$notebookId'
    | '/app/focus/new'
    | '/app/meetings/$meetingId'
    | '/app/meetings/start'
    | '/app/transcribe/add'
    | '/admin/users'
    | '/app/docs'
    | '/app/focus'
    | '/app/knowledge'
    | '/app/transcribe'
    | '/admin/users/$userId/edit'
    | '/app/docs/$kbSlug/edit'
    | '/app/focus/$notebookId/add-source'
    | '/app/focus/$notebookId/edit'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/admin'
    | '/app'
    | '/callback'
    | '/logged-out'
    | '/login'
    | '/provisioning'
    | '/signup'
    | '/verify'
    | '/$locale/signup'
    | '/admin/billing'
    | '/admin/settings'
    | '/app/account'
    | '/app/chat'
    | '/app/scribe'
    | '/password/forgot'
    | '/password/set'
    | '/setup/2fa'
    | '/setup/mfa'
    | '/admin/'
    | '/app/'
    | '/$locale/password/forgot'
    | '/admin/users/invite'
    | '/app/docs/$kbSlug'
    | '/app/docs/new'
    | '/app/focus/$notebookId'
    | '/app/focus/new'
    | '/app/meetings/$meetingId'
    | '/app/meetings/start'
    | '/app/transcribe/add'
    | '/admin/users/'
    | '/app/docs/'
    | '/app/focus/'
    | '/app/knowledge/'
    | '/app/transcribe/'
    | '/admin/users/$userId/edit'
    | '/app/docs/$kbSlug_/edit'
    | '/app/focus/$notebookId_/add-source'
    | '/app/focus/$notebookId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LoggedOutRoute: typeof LoggedOutRoute
  LoginRoute: typeof LoginRoute
  ProvisioningRoute: typeof ProvisioningRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
  PasswordForgotRoute: typeof PasswordForgotRoute
  PasswordSetRoute: typeof PasswordSetRoute
  Setup2faRoute: typeof Setup2faRoute
  SetupMfaRoute: typeof SetupMfaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provisioning': {
      id: '/provisioning'
      path: '/provisioning'
      fullPath: '/provisioning'
      preLoaderRoute: typeof ProvisioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logged-out': {
      id: '/logged-out'
      path: '/logged-out'
      fullPath: '/logged-out'
      preLoaderRoute: typeof LoggedOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/setup/mfa': {
      id: '/setup/mfa'
      path: '/setup/mfa'
      fullPath: '/setup/mfa'
      preLoaderRoute: typeof SetupMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/2fa': {
      id: '/setup/2fa'
      path: '/setup/2fa'
      fullPath: '/setup/2fa'
      preLoaderRoute: typeof Setup2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/set': {
      id: '/password/set'
      path: '/password/set'
      fullPath: '/password/set'
      preLoaderRoute: typeof PasswordSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/forgot': {
      id: '/password/forgot'
      path: '/password/forgot'
      fullPath: '/password/forgot'
      preLoaderRoute: typeof PasswordForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/scribe': {
      id: '/app/scribe'
      path: '/scribe'
      fullPath: '/app/scribe'
      preLoaderRoute: typeof AppScribeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$locale/signup': {
      id: '/$locale/signup'
      path: '/signup'
      fullPath: '/$locale/signup'
      preLoaderRoute: typeof LocaleSignupRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/app/transcribe/': {
      id: '/app/transcribe/'
      path: '/transcribe'
      fullPath: '/app/transcribe/'
      preLoaderRoute: typeof AppTranscribeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/knowledge/': {
      id: '/app/knowledge/'
      path: '/knowledge'
      fullPath: '/app/knowledge/'
      preLoaderRoute: typeof AppKnowledgeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/focus/': {
      id: '/app/focus/'
      path: '/focus'
      fullPath: '/app/focus/'
      preLoaderRoute: typeof AppFocusIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/docs/': {
      id: '/app/docs/'
      path: '/docs'
      fullPath: '/app/docs/'
      preLoaderRoute: typeof AppDocsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/app/transcribe/add': {
      id: '/app/transcribe/add'
      path: '/transcribe/add'
      fullPath: '/app/transcribe/add'
      preLoaderRoute: typeof AppTranscribeAddRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/meetings/start': {
      id: '/app/meetings/start'
      path: '/meetings/start'
      fullPath: '/app/meetings/start'
      preLoaderRoute: typeof AppMeetingsStartRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/meetings/$meetingId': {
      id: '/app/meetings/$meetingId'
      path: '/meetings/$meetingId'
      fullPath: '/app/meetings/$meetingId'
      preLoaderRoute: typeof AppMeetingsMeetingIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/focus/new': {
      id: '/app/focus/new'
      path: '/focus/new'
      fullPath: '/app/focus/new'
      preLoaderRoute: typeof AppFocusNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/focus/$notebookId': {
      id: '/app/focus/$notebookId'
      path: '/focus/$notebookId'
      fullPath: '/app/focus/$notebookId'
      preLoaderRoute: typeof AppFocusNotebookIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/docs/new': {
      id: '/app/docs/new'
      path: '/docs/new'
      fullPath: '/app/docs/new'
      preLoaderRoute: typeof AppDocsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/docs/$kbSlug': {
      id: '/app/docs/$kbSlug'
      path: '/docs/$kbSlug'
      fullPath: '/app/docs/$kbSlug'
      preLoaderRoute: typeof AppDocsKbSlugRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/users/invite': {
      id: '/admin/users/invite'
      path: '/users/invite'
      fullPath: '/admin/users/invite'
      preLoaderRoute: typeof AdminUsersInviteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$locale/password/forgot': {
      id: '/$locale/password/forgot'
      path: '/password/forgot'
      fullPath: '/$locale/password/forgot'
      preLoaderRoute: typeof LocalePasswordForgotRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/app/focus/$notebookId_/edit': {
      id: '/app/focus/$notebookId_/edit'
      path: '/focus/$notebookId/edit'
      fullPath: '/app/focus/$notebookId/edit'
      preLoaderRoute: typeof AppFocusNotebookIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/focus/$notebookId_/add-source': {
      id: '/app/focus/$notebookId_/add-source'
      path: '/focus/$notebookId/add-source'
      fullPath: '/app/focus/$notebookId/add-source'
      preLoaderRoute: typeof AppFocusNotebookIdAddSourceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/docs/$kbSlug_/edit': {
      id: '/app/docs/$kbSlug_/edit'
      path: '/docs/$kbSlug/edit'
      fullPath: '/app/docs/$kbSlug/edit'
      preLoaderRoute: typeof AppDocsKbSlugEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/users/$userId/edit': {
      id: '/admin/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/admin/users/$userId/edit'
      preLoaderRoute: typeof AdminUsersUserIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleSignupRoute: typeof LocaleSignupRoute
  LocalePasswordForgotRoute: typeof LocalePasswordForgotRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleSignupRoute: LocaleSignupRoute,
  LocalePasswordForgotRoute: LocalePasswordForgotRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminBillingRoute: typeof AdminBillingRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersInviteRoute: typeof AdminUsersInviteRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminUsersUserIdEditRoute: typeof AdminUsersUserIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBillingRoute: AdminBillingRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersInviteRoute: AdminUsersInviteRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminUsersUserIdEditRoute: AdminUsersUserIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppChatRoute: typeof AppChatRoute
  AppScribeRoute: typeof AppScribeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDocsKbSlugRoute: typeof AppDocsKbSlugRoute
  AppDocsNewRoute: typeof AppDocsNewRoute
  AppFocusNotebookIdRoute: typeof AppFocusNotebookIdRoute
  AppFocusNewRoute: typeof AppFocusNewRoute
  AppMeetingsMeetingIdRoute: typeof AppMeetingsMeetingIdRoute
  AppMeetingsStartRoute: typeof AppMeetingsStartRoute
  AppTranscribeAddRoute: typeof AppTranscribeAddRoute
  AppDocsIndexRoute: typeof AppDocsIndexRoute
  AppFocusIndexRoute: typeof AppFocusIndexRoute
  AppKnowledgeIndexRoute: typeof AppKnowledgeIndexRoute
  AppTranscribeIndexRoute: typeof AppTranscribeIndexRoute
  AppDocsKbSlugEditRoute: typeof AppDocsKbSlugEditRoute
  AppFocusNotebookIdAddSourceRoute: typeof AppFocusNotebookIdAddSourceRoute
  AppFocusNotebookIdEditRoute: typeof AppFocusNotebookIdEditRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppChatRoute: AppChatRoute,
  AppScribeRoute: AppScribeRoute,
  AppIndexRoute: AppIndexRoute,
  AppDocsKbSlugRoute: AppDocsKbSlugRoute,
  AppDocsNewRoute: AppDocsNewRoute,
  AppFocusNotebookIdRoute: AppFocusNotebookIdRoute,
  AppFocusNewRoute: AppFocusNewRoute,
  AppMeetingsMeetingIdRoute: AppMeetingsMeetingIdRoute,
  AppMeetingsStartRoute: AppMeetingsStartRoute,
  AppTranscribeAddRoute: AppTranscribeAddRoute,
  AppDocsIndexRoute: AppDocsIndexRoute,
  AppFocusIndexRoute: AppFocusIndexRoute,
  AppKnowledgeIndexRoute: AppKnowledgeIndexRoute,
  AppTranscribeIndexRoute: AppTranscribeIndexRoute,
  AppDocsKbSlugEditRoute: AppDocsKbSlugEditRoute,
  AppFocusNotebookIdAddSourceRoute: AppFocusNotebookIdAddSourceRoute,
  AppFocusNotebookIdEditRoute: AppFocusNotebookIdEditRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoggedOutRoute: LoggedOutRoute,
  LoginRoute: LoginRoute,
  ProvisioningRoute: ProvisioningRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
  PasswordForgotRoute: PasswordForgotRoute,
  PasswordSetRoute: PasswordSetRoute,
  Setup2faRoute: Setup2faRoute,
  SetupMfaRoute: SetupMfaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
