"""
Tenant provisioning service.
Called after signup DB commit to set up a new customer's LibreChat instance.
"""
import asyncio
import logging
import secrets
from pathlib import Path

import docker
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.core.config import settings
from app.core.database import AsyncSessionLocal
from app.models.portal import PortalOrg
from app.services.zitadel import zitadel

logger = logging.getLogger(__name__)

# File lock to prevent concurrent Caddyfile writes
_caddy_lock = asyncio.Lock()


def _slugify_unique(name: str, existing_slugs: set[str]) -> str:
    """Generate a unique slug from org name."""
    import re, unicodedata
    n = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode()
    n = re.sub(r"[^a-zA-Z0-9\s-]", "", n)
    n = re.sub(r"\s+", "-", n).strip("-").lower()
    n = n[:50] or "org"
    slug = n
    counter = 2
    while slug in existing_slugs:
        slug = f"{n}-{counter}"
        counter += 1
    return slug


def _generate_librechat_env(slug: str, client_id: str, client_secret: str) -> str:
    """Generate the per-tenant LibreChat .env file content."""
    domain = settings.domain
    jwt_secret = secrets.token_hex(32)
    jwt_refresh_secret = secrets.token_hex(32)
    session_secret = secrets.token_hex(32)
    creds_key = secrets.token_hex(32)
    creds_iv = secrets.token_hex(8)
    mongo_pw = settings.mongo_root_password

    return f"""# Auto-generated by portal-api at provisioning. Do not edit manually.
# Tenant: {slug}

# MongoDB -- tenant-isolated database
MONGO_URI=mongodb://klai:{mongo_pw}@mongodb:27017/librechat-{slug}?authSource=admin

# Zitadel OIDC
OPENID_ISSUER=https://auth.{domain}
OPENID_CLIENT_ID={client_id}
OPENID_CLIENT_SECRET={client_secret}
OPENID_SCOPE=openid profile email
OPENID_CALLBACK_URL=/oauth/openid/callback
OPENID_USERNAME_CLAIM=preferred_username
OPENID_REUSE_TOKENS=false
OPENID_USE_END_SESSION_ENDPOINT=true
ALLOW_EMAIL_LOGIN=false
ALLOW_REGISTRATION=false
ALLOW_SOCIAL_LOGIN=true
ALLOW_SOCIAL_REGISTRATION=true

# App settings
DOMAIN_CLIENT=https://chat.{slug}.{domain}
DOMAIN_SERVER=https://chat.{slug}.{domain}
APP_TITLE=Klai Chat

# Session secrets
JWT_SECRET={jwt_secret}
JWT_REFRESH_SECRET={jwt_refresh_secret}
OPENID_SESSION_SECRET={session_secret}
CREDS_KEY={creds_key}
CREDS_IV={creds_iv}

# Search
MEILI_HOST=http://meilisearch:7700
MEILI_MASTER_KEY={settings.meili_master_key}

# AI routing via LiteLLM
LITELLM_API_KEY={settings.litellm_master_key}
"""


def _append_caddy_block(slug: str) -> None:
    """Append a new tenant LibreChat block to the Caddyfile (synchronous, called under lock)."""
    domain = settings.domain
    caddy_path = Path(settings.caddy_config_path)
    block = f"""
# Tenant: {slug}
chat.{slug}.{domain} {{
    tls {{
        dns hetzner {{env.HETZNER_AUTH_API_TOKEN}}
        propagation_delay 120s
    }}
    reverse_proxy librechat-{slug}:3080
}}
"""
    with caddy_path.open("a") as f:
        f.write(block)


def _reload_caddy() -> None:
    """Restart the Caddy container so it picks up the updated Caddyfile.

    Caddy admin API is disabled (admin off); restarting is the safe alternative.
    docker-socket-proxy allows POST (restart) on CONTAINERS.
    """
    client = docker.from_env()
    caddy = client.containers.get(settings.caddy_container_name)
    caddy.restart(timeout=10)


def _start_librechat_container(slug: str, env_file_host_path: str) -> None:
    """Start the LibreChat Docker container for a tenant (synchronous, run in executor)."""
    client = docker.from_env()
    container_name = f"librechat-{slug}"

    # Remove stale container if it exists (e.g. failed previous provisioning)
    try:
        old = client.containers.get(container_name)
        old.remove(force=True)
    except docker.errors.NotFound:
        pass

    librechat_host_base = settings.librechat_host_data_path
    client.containers.run(
        image=settings.librechat_image,
        name=container_name,
        detach=True,
        restart_policy={"Name": "unless-stopped"},
        volumes={
            env_file_host_path: {"bind": "/app/.env", "mode": "ro"},
            f"{librechat_host_base}/librechat.yaml": {"bind": "/app/librechat.yaml", "mode": "ro"},
            f"{librechat_host_base}/{slug}/images": {"bind": "/app/client/public/images", "mode": "rw"},
        },
        network="klai-net",
    )

    # Connect to additional networks
    for net_name in ["klai-net-mongodb", "klai-net-meilisearch"]:
        try:
            net = client.networks.get(net_name)
            net.connect(container_name)
        except Exception as exc:
            logger.warning("Could not connect %s to %s: %s", container_name, net_name, exc)


async def provision_tenant(org_id: int) -> None:
    """
    Full tenant provisioning. Called as a BackgroundTask after signup.
    Opens its own DB session (the request session is closed by the time this runs).
    Updates the PortalOrg row with provisioning results.
    """
    async with AsyncSessionLocal() as db:
        await _provision(org_id, db)


async def _provision(org_id: int, db: AsyncSession) -> None:
    # Fetch org
    result = await db.execute(select(PortalOrg).where(PortalOrg.id == org_id))
    org = result.scalar_one()

    # Get existing slugs to ensure uniqueness
    from sqlalchemy import func as sa_func
    slugs_result = await db.execute(select(PortalOrg.slug))
    existing_slugs = {row[0] for row in slugs_result.fetchall() if row[0]}

    slug = _slugify_unique(org.name, existing_slugs)
    logger.info("Provisioning tenant %s (org_id=%d)", slug, org_id)

    try:
        # Step 1: Zitadel OIDC app for LibreChat
        redirect_uri = f"https://chat.{slug}.{settings.domain}/oauth/openid/callback"
        oidc_data = await zitadel.create_librechat_oidc_app(slug, redirect_uri)
        client_id = oidc_data.get("clientId", "")
        client_secret = oidc_data.get("clientSecret", "")
        logger.info("Created Zitadel OIDC app for %s: %s", slug, client_id)

        # Step 2: Add portal redirect URI for this tenant
        try:
            await zitadel.add_portal_redirect_uri(slug)
        except Exception as exc:
            logger.warning("Could not add portal redirect URI for %s: %s", slug, exc)

        # Step 3: Write LibreChat .env file
        env_content = _generate_librechat_env(slug, client_id, client_secret)
        container_data_base = Path(settings.librechat_container_data_path)
        tenant_dir = container_data_base / slug
        tenant_dir.mkdir(parents=True, exist_ok=True)
        (tenant_dir / "images").mkdir(exist_ok=True)
        env_file_container_path = tenant_dir / ".env"
        env_file_container_path.write_text(env_content)
        # Host path for Docker volume mount
        env_file_host_path = f"{settings.librechat_host_data_path}/{slug}/.env"
        logger.info("Wrote LibreChat .env for %s", slug)

        # Step 4: Start Docker container
        loop = asyncio.get_running_loop()
        await loop.run_in_executor(
            None, _start_librechat_container, slug, env_file_host_path
        )
        logger.info("Started container librechat-%s", slug)

        # Step 5: Append Caddyfile block + restart Caddy (admin API is disabled)
        async with _caddy_lock:
            _append_caddy_block(slug)
            await loop.run_in_executor(None, _reload_caddy)
        logger.info("Caddy restarted for %s", slug)

        # Step 6: Update DB
        org.slug = slug
        org.librechat_container = f"librechat-{slug}"
        org.zitadel_librechat_client_id = client_id
        org.zitadel_librechat_client_secret = client_secret
        org.provisioning_status = "ready"
        await db.commit()
        logger.info("Tenant %s provisioning complete", slug)

    except Exception as exc:
        logger.error("Provisioning failed for org_id=%d: %s", org_id, exc, exc_info=True)
        try:
            org.provisioning_status = "failed"
            await db.commit()
        except Exception:
            pass
        raise
