import fs from "fs/promises";
import path from "path";

const TENANTS_DIR = process.env.CADDY_TENANTS_DIR ?? "/etc/caddy/tenants";

/**
 * Write a Caddy site block for an org subdomain that routes to docs-app.
 * The file is picked up by Caddy's `import /etc/caddy/tenants/*.caddyfile`.
 *
 * After writing, Caddy must be reloaded:
 *   docker exec caddy caddy reload --config /etc/caddy/Caddyfile
 */
export async function writeTenantCaddyfile(orgSlug: string, baseDomain: string) {
  const content = `# Auto-generated by klai-docs — do not edit manually
# Org: ${orgSlug}
${orgSlug}.${baseDomain} {
    reverse_proxy docs-app:3010
}
`;
  const filePath = path.join(TENANTS_DIR, `docs-${orgSlug}.caddyfile`);
  await fs.writeFile(filePath, content, "utf-8");
}

export async function removeTenantCaddyfile(orgSlug: string) {
  const filePath = path.join(TENANTS_DIR, `docs-${orgSlug}.caddyfile`);
  await fs.rm(filePath, { force: true });
}

/**
 * Add a custom domain to an existing caddyfile or create a new one.
 */
export async function writeCustomDomainCaddyfile(domain: string) {
  const content = `# Auto-generated by klai-docs — do not edit manually
# Custom domain: ${domain}
${domain} {
    reverse_proxy docs-app:3010
}
`;
  const safeName = domain.replace(/[^a-z0-9.-]/gi, "_");
  const filePath = path.join(TENANTS_DIR, `docs-custom-${safeName}.caddyfile`);
  await fs.writeFile(filePath, content, "utf-8");
}
