"""
Provisioning generators: slug, .env, and librechat.yaml generation.

These functions are pure generators with no side effects on external systems.
"""

import copy
import re
import secrets
import unicodedata
from pathlib import Path
from urllib.parse import quote

import structlog
import yaml

from app.core.config import settings
from app.services.secrets import decrypt_mcp_secret, is_secret_var

logger = structlog.get_logger()


def _slugify_unique(name: str, existing_slugs: set[str]) -> str:
    """Generate a unique slug from org name."""
    n = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode()
    n = re.sub(r"[^a-zA-Z0-9\s-]", "", n)
    n = re.sub(r"\s+", "-", n).strip("-").lower()
    n = n[:50] or "org"
    slug = n
    counter = 2
    while slug in existing_slugs:
        slug = f"{n}-{counter}"
        counter += 1
    return slug


def _generate_librechat_yaml(
    base_path: Path,
    mcp_servers: dict | None,
) -> str:
    """Generate a per-tenant librechat.yaml from base config + catalog-validated MCP servers.

    Loads the MCP catalog from <base_path.parent>/mcp_catalog.yaml and validates each enabled
    entry against it. Unknown server IDs are skipped with a warning (REQ-S-002).
    config_template from the catalog is used verbatim — ${VAR} placeholders are expanded by
    LibreChat at runtime from the container .env file.

    Returns the YAML string.
    """
    with open(base_path) as f:
        config = yaml.safe_load(f)

    if not mcp_servers:
        return yaml.dump(config, default_flow_style=False, sort_keys=False)

    # Load MCP catalog (whitelist of supported servers)
    catalog_path = base_path.parent / "mcp_catalog.yaml"
    try:
        with open(catalog_path) as f:
            catalog = yaml.safe_load(f)
    except FileNotFoundError:
        logger.warning("mcp_catalog_not_found", path=str(catalog_path))
        return yaml.dump(config, default_flow_style=False, sort_keys=False)

    catalog_servers = catalog.get("servers", {})
    config = copy.deepcopy(config)
    mcp_section = config.setdefault("mcpServers", {})
    enabled_names: list[str] = []

    for server_id, server_cfg in mcp_servers.items():
        if not server_cfg.get("enabled", False):
            continue
        if server_id not in catalog_servers:
            # REQ-S-002: unknown entries are skipped, not raised as an error
            logger.warning("mcp_server_not_in_catalog", server_id=server_id)
            continue
        mcp_section[server_id] = catalog_servers[server_id]["config_template"]
        enabled_names.append(server_id)

    if enabled_names:
        for spec in config.get("modelSpecs", {}).get("list", []):
            existing = spec.get("mcpServers", [])
            spec["mcpServers"] = existing + enabled_names

    return yaml.dump(config, default_flow_style=False, sort_keys=False)


def _generate_librechat_env(
    slug: str,
    client_id: str,
    client_secret: str,
    litellm_api_key: str,
    mongo_password: str,
    zitadel_org_id: str = "",
    mcp_servers: dict | None = None,
) -> str:
    """Generate the per-tenant LibreChat .env file content."""
    domain = settings.domain
    jwt_secret = secrets.token_hex(32)
    jwt_refresh_secret = secrets.token_hex(32)
    session_secret = secrets.token_hex(32)
    creds_key = secrets.token_hex(32)
    creds_iv = secrets.token_hex(8)

    # Build MCP server env vars (decrypted from DB; REQ-N-001: no secrets in logs)
    mcp_env_lines: list[str] = []
    if mcp_servers:
        for server_id, server_cfg in mcp_servers.items():
            if not server_cfg.get("enabled", False):
                continue
            env_vars = server_cfg.get("env", {})
            if env_vars:
                mcp_env_lines.append(f"\n# MCP server: {server_id}")
                for var_name, encrypted_or_plain in env_vars.items():
                    if is_secret_var(var_name):
                        try:
                            value = decrypt_mcp_secret(encrypted_or_plain)
                        except ValueError:
                            logger.warning(  # nosemgrep: python-logger-credential-disclosure
                                "mcp_secret_decryption_failed",
                                server_id=server_id,
                                var_name=var_name,
                            )
                            continue
                    else:
                        value = encrypted_or_plain
                    mcp_env_lines.append(f"{var_name}={value}")

    mcp_env_block = "\n".join(mcp_env_lines)

    return f"""# Auto-generated by portal-api at provisioning. Do not edit manually.
# Tenant: {slug}

# MongoDB -- tenant-isolated database (per-tenant user, NOT the shared admin)
MONGO_URI=mongodb://librechat-{slug}:{mongo_password}@mongodb:27017/librechat-{slug}?authSource=librechat-{slug}

# Zitadel OIDC
OPENID_ISSUER=https://auth.{domain}
OPENID_CLIENT_ID={client_id}
OPENID_CLIENT_SECRET={client_secret}
OPENID_SCOPE=openid profile email
OPENID_CALLBACK_URL=/oauth/openid/callback
OPENID_USERNAME_CLAIM=preferred_username
OPENID_REUSE_TOKENS=false
OPENID_USE_END_SESSION_ENDPOINT=true
ALLOW_EMAIL_LOGIN=false
ALLOW_REGISTRATION=false
ALLOW_SOCIAL_LOGIN=true
ALLOW_SOCIAL_REGISTRATION=false

# Login rate limiting -- raised from the default (7) because LibreChat's
# loginLimiter counts every OAuth route hit (redirect + callback = 2 per OIDC
# cycle).  With ALLOW_EMAIL_LOGIN=false there is no brute-force vector at this
# layer; credential protection is handled by Zitadel's lockout policy and
# Caddy's per-IP rate_limit block.  250 allows ~125 OIDC cycles per window.
# NOTE: express-rate-limit v7+ blocks all requests when max=0 (not "unlimited").
LOGIN_MAX=250

# App settings
DOMAIN_CLIENT=https://chat-{slug}.{domain}
DOMAIN_SERVER=https://chat-{slug}.{domain}
APP_TITLE=Klai Chat
ALLOW_IFRAME=true

# Session secrets
JWT_SECRET={jwt_secret}
JWT_REFRESH_SECRET={jwt_refresh_secret}
OPENID_SESSION_SECRET={session_secret}
CREDS_KEY={creds_key}
CREDS_IV={creds_iv}

# Session lifetime -- access token: 7 days, refresh token: 30 days.
# Ensures users stay logged in across weekends and container restarts without
# needing to re-enter password + 2FA. Zitadel session should be configured
# to at least 30 days to match (auth.getklai.com → Login Policy → Session Lifetime).
SESSION_EXPIRY=604800000
REFRESH_TOKEN_EXPIRY=2592000000

# Search
MEILI_HOST=http://meilisearch:7700
MEILI_MASTER_KEY={settings.meili_master_key}

# Redis (session persistence across container restarts)
REDIS_URI=redis://:{quote(settings.redis_password, safe="")}@redis:6379

# AI routing via LiteLLM
LITELLM_API_KEY={litellm_api_key}

# Web search (shared services on klai-net)
SEARXNG_INSTANCE_URL=http://searxng:8080
FIRECRAWL_API_KEY={settings.firecrawl_internal_key}
FIRECRAWL_API_URL=http://firecrawl-api:3002
JINA_API_KEY=klai-internal
JINA_API_URL=http://infinity-reranker:7997/v1/rerank

# Klai Knowledge MCP identity (used by librechat.yaml ${{...}} expansion)
KLAI_ZITADEL_ORG_ID={zitadel_org_id}
KLAI_ORG_SLUG={slug}
KNOWLEDGE_INGEST_SECRET={settings.knowledge_ingest_secret}
{mcp_env_block}
"""
