"""Tests for SPEC-TENANT-ENV-RECONCILE-001: additive per-tenant .env reconciliation.

``reconcile_librechat_env`` backfills newly-introduced env vars (e.g.
PORTAL_INTERNAL_URL / PORTAL_INTERNAL_SECRET from SPEC-KB-015) into tenant
.env files that were provisioned before those vars existed.

[HARD SAFETY INVARIANT] ``_generate_librechat_env`` mints a fresh
``secrets.token_hex(...)`` on every call for JWT_SECRET / JWT_REFRESH_SECRET /
OPENID_SESSION_SECRET / CREDS_KEY / CREDS_IV. CREDS_KEY/CREDS_IV encrypt
user-stored LibreChat credentials in MongoDB -- regenerating a tenant's .env
wholesale would rotate those and make existing user data undecryptable, and
would log every user out. These tests pin that reconciliation is strictly
additive: it must never rewrite, reorder, or rotate an existing line.
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest

from app.services.provisioning.generators import (
    EnvFileMissingError,
    reconcile_librechat_env,
)

EXISTING_ENV = """# Auto-generated by portal-api at provisioning. Do not edit manually.
# Tenant: acme

# MongoDB -- tenant-isolated database (per-tenant user, NOT the shared admin)
MONGO_URI=mongodb://librechat-acme:s3cr3t@mongodb:27017/librechat-acme?authSource=librechat-acme

# Session secrets
JWT_SECRET=deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef
JWT_REFRESH_SECRET=cafebabecafebabecafebabecafebabecafebabecafebabecafebabecafebabe
OPENID_SESSION_SECRET=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcd
CREDS_KEY=feedfacefeedfacefeedfacefeedfacefeedfacefeedfacefeedfacefeedface
CREDS_IV=1234567890abcdef
"""


@pytest.fixture()
def existing_env_file(tmp_path: Path) -> Path:
    env_path = tmp_path / ".env"
    env_path.write_text(EXISTING_ENV)
    return env_path


class TestMissingKeyIsAppended:
    def test_missing_key_appended_pre_existing_lines_byte_identical(self, existing_env_file: Path):
        """(a) A missing key is appended; every pre-existing line survives untouched."""
        added = reconcile_librechat_env(existing_env_file, {"PORTAL_INTERNAL_URL": "http://portal-api:8010"})

        assert added == ["PORTAL_INTERNAL_URL"]
        new_content = existing_env_file.read_text()

        # Every original line is present, in the same order, byte-identical.
        original_lines = EXISTING_ENV.splitlines()
        new_lines = new_content.splitlines()
        assert new_lines[: len(original_lines)] == original_lines

        # The new key was appended after the original content, under a marker.
        assert "PORTAL_INTERNAL_URL=http://portal-api:8010" in new_content
        assert "# --- klai managed additions (reconciled " in new_content
        marker_index = new_content.index("# --- klai managed additions")
        added_index = new_content.index("PORTAL_INTERNAL_URL=http://portal-api:8010")
        assert marker_index < added_index

    def test_multiple_missing_keys_all_appended(self, existing_env_file: Path):
        added = reconcile_librechat_env(
            existing_env_file,
            {
                "PORTAL_INTERNAL_URL": "http://portal-api:8010",
                "PORTAL_INTERNAL_SECRET": "super-secret-value",
            },
        )

        assert added == ["PORTAL_INTERNAL_URL", "PORTAL_INTERNAL_SECRET"]
        new_content = existing_env_file.read_text()
        assert "PORTAL_INTERNAL_URL=http://portal-api:8010" in new_content
        assert "PORTAL_INTERNAL_SECRET=super-secret-value" in new_content


class TestAlreadyPresentKeyIsNoOp:
    def test_already_present_key_is_a_true_no_op(self, existing_env_file: Path):
        """(b) An already-present key triggers no write at all -- content and mtime unchanged."""
        before_content = existing_env_file.read_text()
        before_mtime_ns = existing_env_file.stat().st_mtime_ns

        added = reconcile_librechat_env(existing_env_file, {"JWT_SECRET": "some-new-value-that-must-be-ignored"})

        assert added == []
        after_content = existing_env_file.read_text()
        after_mtime_ns = existing_env_file.stat().st_mtime_ns

        assert after_content == before_content
        assert after_mtime_ns == before_mtime_ns
        # The bogus replacement value must never appear -- proves no rewrite happened.
        assert "some-new-value-that-must-be-ignored" not in after_content

    def test_mixed_present_and_missing_only_appends_missing(self, existing_env_file: Path):
        added = reconcile_librechat_env(
            existing_env_file,
            {
                "JWT_SECRET": "attempted-rotation-value",
                "PORTAL_INTERNAL_URL": "http://portal-api:8010",
            },
        )

        assert added == ["PORTAL_INTERNAL_URL"]
        new_content = existing_env_file.read_text()
        assert "attempted-rotation-value" not in new_content
        assert "PORTAL_INTERNAL_URL=http://portal-api:8010" in new_content
        # Original JWT_SECRET line is unchanged.
        assert "JWT_SECRET=deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef" in new_content


class TestValueContainingEqualsSign:
    def test_value_with_equals_sign_parsed_as_present_not_duplicated(self, existing_env_file: Path):
        """(c) MONGO_URI's value contains '=' (authSource=...) -- must be detected as
        present (key-only match) and not duplicated even if passed in ``required``.
        """
        added = reconcile_librechat_env(
            existing_env_file,
            {"MONGO_URI": "mongodb://someone-else:pw@mongodb:27017/other?authSource=other"},
        )

        assert added == []
        new_content = existing_env_file.read_text()
        # Original URI is untouched; the bogus replacement never appears.
        assert "MONGO_URI=mongodb://librechat-acme:s3cr3t@mongodb:27017/librechat-acme?authSource=librechat-acme" in (
            new_content
        )
        assert "someone-else" not in new_content
        # Exactly one MONGO_URI= line in the file.
        assert new_content.count("MONGO_URI=") == 1


class TestMissingEnvFileIsAnError:
    def test_missing_env_file_raises_and_creates_nothing(self, tmp_path: Path):
        """(d) A missing .env file is reported as an error, not papered over."""
        env_path = tmp_path / ".env"
        assert not env_path.exists()

        with pytest.raises(EnvFileMissingError):
            reconcile_librechat_env(env_path, {"PORTAL_INTERNAL_URL": "http://portal-api:8010"})

        assert not env_path.exists()
        assert list(tmp_path.iterdir()) == []


class TestAtomicWriteLeavesNoTempFile:
    def test_new_file_does_not_survive_the_write(self, existing_env_file: Path):
        """(e) The atomic write path (write .new, chmod 600, os.replace) leaves
        no .new file behind, win or lose.
        """
        reconcile_librechat_env(existing_env_file, {"PORTAL_INTERNAL_URL": "http://portal-api:8010"})

        tmp_path_candidate = existing_env_file.parent / f"{existing_env_file.name}.new"
        assert not tmp_path_candidate.exists()
        assert [p.name for p in existing_env_file.parent.iterdir()] == [".env"]

    def test_final_file_permissions_are_owner_only(self, existing_env_file: Path):
        reconcile_librechat_env(existing_env_file, {"PORTAL_INTERNAL_URL": "http://portal-api:8010"})

        mode = existing_env_file.stat().st_mode & 0o777
        assert mode == 0o600


class TestNoOpDoesNotTouchFilesystemAtAll:
    def test_no_missing_keys_means_no_write_call(self, existing_env_file: Path, monkeypatch: pytest.MonkeyPatch):
        """When nothing is missing, reconcile must not even attempt os.replace --
        pins the "not even a mtime bump" contract documented on the function.
        """
        replace_calls: list[tuple[str, str]] = []
        real_replace = os.replace

        def _tracking_replace(src: str, dst: str) -> None:
            replace_calls.append((str(src), str(dst)))
            real_replace(src, dst)

        monkeypatch.setattr(os, "replace", _tracking_replace)

        added = reconcile_librechat_env(existing_env_file, {"JWT_SECRET": "irrelevant"})

        assert added == []
        assert replace_calls == []


class TestSecretRotationSafetyInvariant:
    """(g) The core safety invariant: CREDS_KEY / CREDS_IV / JWT_SECRET-style
    existing values are NEVER rotated by reconciliation, no matter what value
    is passed in ``required`` for that key. This is what prevents existing
    user-stored LibreChat credentials (encrypted with CREDS_KEY/CREDS_IV) from
    becoming undecryptable and every user being logged out.
    """

    def test_creds_key_and_jwt_secret_are_never_rotated(self, existing_env_file: Path):
        original_creds_key = "feedfacefeedfacefeedfacefeedfacefeedfacefeedfacefeedfacefeedface"
        original_creds_iv = "1234567890abcdef"
        original_jwt_secret = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
        original_jwt_refresh = "cafebabecafebabecafebabecafebabecafebabecafebabecafebabecafebabe"
        original_session_secret = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcd"

        # A malicious/buggy caller passes brand-new secret values for every
        # rotation-sensitive key -- reconcile must ignore all of them because
        # every one of these keys already exists in the file.
        added = reconcile_librechat_env(
            existing_env_file,
            {
                "CREDS_KEY": "0" * 64,
                "CREDS_IV": "0" * 16,
                "JWT_SECRET": "1" * 64,
                "JWT_REFRESH_SECRET": "2" * 64,
                "OPENID_SESSION_SECRET": "3" * 64,
            },
        )

        assert added == [], "no rotation-sensitive key should ever be reported as added when already present"

        final_content = existing_env_file.read_text()
        assert f"CREDS_KEY={original_creds_key}" in final_content
        assert f"CREDS_IV={original_creds_iv}" in final_content
        assert f"JWT_SECRET={original_jwt_secret}" in final_content
        assert f"JWT_REFRESH_SECRET={original_jwt_refresh}" in final_content
        assert f"OPENID_SESSION_SECRET={original_session_secret}" in final_content

        # None of the attempted-rotation values leaked into the file.
        assert "0" * 64 not in final_content
        assert "1" * 64 not in final_content
        assert "2" * 64 not in final_content
        assert "3" * 64 not in final_content
