"""
Characterization tests for _generate_librechat_env() and _generate_librechat_yaml().

These tests capture the current behavior of the env/yaml generators so that
structural changes (adding parameters, new env vars) can be verified
against the existing output format.
"""

import re
import textwrap
from unittest.mock import patch

import pytest
import yaml


@pytest.fixture(autouse=True)
def _mock_settings():
    """Provide deterministic settings for all tests."""
    import app.services.provisioning.generators  # ensure module is imported before patching  # noqa: F401

    with patch("app.services.provisioning.generators.settings") as mock:
        mock.domain = "getklai.com"
        mock.mongo_root_password = "test-mongo-pw"
        mock.meili_master_key = "test-meili-key"
        mock.redis_password = "test-redis-pw"
        mock.litellm_master_key = "test-litellm-master"
        mock.firecrawl_internal_key = "test-firecrawl-key"
        mock.knowledge_ingest_secret = "test-knowledge-secret"
        yield mock


@pytest.fixture()
def _mock_secrets():
    """Provide deterministic secrets for snapshot tests."""
    with patch("app.services.provisioning.generators.secrets") as mock:
        mock.token_hex = lambda n: f"{'ab' * n}"
        yield mock


class TestCharacterizeGenerateLibrechatEnv:
    """Characterization tests: document what _generate_librechat_env currently produces."""

    def test_characterize_output_contains_all_required_sections(self):
        """The env output must contain all expected sections."""
        from app.services.provisioning import _generate_librechat_env

        result = _generate_librechat_env(
            slug="acme",
            client_id="cid-123",
            client_secret="csec-456",  # noqa: S106
            litellm_api_key="test-litellm-master",
            mongo_password="test-tenant-pw",  # noqa: S106
        )

        # MongoDB section
        assert "MONGO_URI=mongodb://librechat-acme:test-tenant-pw@mongodb:27017" in result
        assert "authSource=librechat-acme" in result

        # Zitadel OIDC section
        assert "OPENID_ISSUER=https://auth.getklai.com" in result
        assert "OPENID_CLIENT_ID=cid-123" in result
        assert "OPENID_CLIENT_SECRET=csec-456" in result
        assert "OPENID_SCOPE=openid profile email" in result
        assert "ALLOW_EMAIL_LOGIN=false" in result
        assert "ALLOW_SOCIAL_LOGIN=true" in result

        # App settings
        assert "DOMAIN_CLIENT=https://chat-acme.getklai.com" in result
        assert "DOMAIN_SERVER=https://chat-acme.getklai.com" in result
        assert "APP_TITLE=Klai Chat" in result

        # Session secrets (non-deterministic, just check they exist)
        assert "JWT_SECRET=" in result
        assert "JWT_REFRESH_SECRET=" in result
        assert "OPENID_SESSION_SECRET=" in result
        assert "CREDS_KEY=" in result
        assert "CREDS_IV=" in result

        # Search
        assert "MEILI_HOST=http://meilisearch:7700" in result
        assert "MEILI_MASTER_KEY=test-meili-key" in result

        # Redis
        assert "REDIS_URI=redis://:test-redis-pw@redis:6379" in result

        # LiteLLM — falls back to master key when no team key provided
        assert "LITELLM_API_KEY=test-litellm-master" in result

    def test_characterize_litellm_team_key_overrides_master(self):
        """When a team key is provided, it replaces the master key."""
        from app.services.provisioning import _generate_librechat_env

        result = _generate_librechat_env(
            slug="acme",
            client_id="cid",
            client_secret="csec",  # noqa: S106
            litellm_api_key="sk-team-key",
            mongo_password="pw",  # noqa: S106
        )

        assert "LITELLM_API_KEY=sk-team-key" in result
        assert "test-litellm-master" not in result

    def test_characterize_slug_appears_in_mongo_and_domain(self):
        """The slug is used consistently in MONGO_URI and DOMAIN_*."""
        from app.services.provisioning import _generate_librechat_env

        result = _generate_librechat_env(
            slug="my-tenant",
            client_id="cid",
            client_secret="csec",  # noqa: S106
            litellm_api_key="key",
            mongo_password="pw",  # noqa: S106
        )

        assert "librechat-my-tenant" in result
        assert "chat-my-tenant.getklai.com" in result

    def test_characterize_output_starts_with_comment_header(self):
        """The output begins with auto-generated comments."""
        from app.services.provisioning import _generate_librechat_env

        result = _generate_librechat_env(
            slug="test-org",
            client_id="cid",
            client_secret="csec",  # noqa: S106
            litellm_api_key="key",
            mongo_password="pw",  # noqa: S106
        )

        lines = result.strip().split("\n")
        assert lines[0] == "# Auto-generated by portal-api at provisioning. Do not edit manually."
        assert lines[1] == "# Tenant: test-org"

    def test_characterize_env_line_format(self):
        """All non-comment non-empty lines follow KEY=VALUE format."""
        from app.services.provisioning import _generate_librechat_env

        result = _generate_librechat_env(
            slug="acme",
            client_id="cid",
            client_secret="csec",  # noqa: S106
            litellm_api_key="key",
            mongo_password="pw",  # noqa: S106
        )

        for line in result.strip().split("\n"):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            assert "=" in line, f"Non-comment line missing '=': {line}"
            key = line.split("=", 1)[0]
            assert re.match(r"^[A-Z_]+$", key), f"Invalid env key: {key}"

    def test_characterize_secrets_are_hex_strings(self):
        """Session secrets are hex-encoded random values."""
        from app.services.provisioning import _generate_librechat_env

        result = _generate_librechat_env(
            slug="acme",
            client_id="cid",
            client_secret="csec",  # noqa: S106
            litellm_api_key="key",
            mongo_password="pw",  # noqa: S106
        )

        env = {}
        for line in result.strip().split("\n"):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            k, v = line.split("=", 1)
            env[k] = v

        for key in ("JWT_SECRET", "JWT_REFRESH_SECRET", "OPENID_SESSION_SECRET", "CREDS_KEY"):
            assert re.match(r"^[0-9a-f]+$", env[key]), f"{key} is not a hex string: {env[key]}"

    def test_characterize_return_type_is_string(self):
        """The function returns a plain string."""
        from app.services.provisioning import _generate_librechat_env

        result = _generate_librechat_env(
            slug="acme",
            client_id="cid",
            client_secret="csec",  # noqa: S106
            litellm_api_key="key",
            mongo_password="pw",  # noqa: S106
        )

        assert isinstance(result, str)


class TestGenerateLibrechatEnvKnowledgeVars:
    """Tests for SPEC-KNOW-003 additions: KLAI_ZITADEL_ORG_ID and KLAI_ORG_SLUG."""

    def test_zitadel_org_id_written_to_env(self):
        """KLAI_ZITADEL_ORG_ID appears in the output when provided."""
        from app.services.provisioning import _generate_librechat_env

        result = _generate_librechat_env(
            slug="acme",
            client_id="cid",
            client_secret="csec",  # noqa: S106
            litellm_api_key="key",
            mongo_password="pw",  # noqa: S106
            zitadel_org_id="362771533686374406",
        )

        assert "KLAI_ZITADEL_ORG_ID=362771533686374406" in result

    def test_org_slug_written_to_env(self):
        """KLAI_ORG_SLUG appears in the output matching the slug parameter."""
        from app.services.provisioning import _generate_librechat_env

        result = _generate_librechat_env(
            slug="acme",
            client_id="cid",
            client_secret="csec",  # noqa: S106
            litellm_api_key="key",
            mongo_password="pw",  # noqa: S106
            zitadel_org_id="123",
        )

        assert "KLAI_ORG_SLUG=acme" in result

    def test_zitadel_org_id_defaults_to_empty(self):
        """When zitadel_org_id is not provided, it defaults to empty string."""
        from app.services.provisioning import _generate_librechat_env

        result = _generate_librechat_env(
            slug="acme",
            client_id="cid",
            client_secret="csec",  # noqa: S106
            litellm_api_key="key",
            mongo_password="pw",  # noqa: S106
        )

        assert "KLAI_ZITADEL_ORG_ID=" in result
        assert "KLAI_ORG_SLUG=acme" in result

    def test_existing_env_vars_still_present_after_addition(self):
        """Adding new vars does not break existing ones (behavior preservation)."""
        from app.services.provisioning import _generate_librechat_env

        result = _generate_librechat_env(
            slug="acme",
            client_id="cid-123",
            client_secret="csec-456",  # noqa: S106
            litellm_api_key="key",
            mongo_password="pw",  # noqa: S106
            zitadel_org_id="org-id-789",
        )

        # All original sections still present
        assert "MONGO_URI=" in result
        assert "OPENID_CLIENT_ID=cid-123" in result
        assert "JWT_SECRET=" in result
        assert "LITELLM_API_KEY=" in result
        assert "KLAI_ZITADEL_ORG_ID=org-id-789" in result
        assert "KLAI_ORG_SLUG=acme" in result


class TestGenerateLibrechatEnvKnowledgeIngestSecret:
    """Tests for SPEC-INFRA-001: KNOWLEDGE_INGEST_SECRET in env template."""

    def test_knowledge_ingest_secret_present_in_env(self):
        """KNOWLEDGE_INGEST_SECRET appears in the output."""
        from app.services.provisioning import _generate_librechat_env

        result = _generate_librechat_env(
            slug="acme",
            client_id="cid",
            client_secret="csec",  # noqa: S106
            litellm_api_key="key",
            mongo_password="pw",  # noqa: S106
        )

        assert "KNOWLEDGE_INGEST_SECRET=test-knowledge-secret" in result


# ── _generate_librechat_yaml tests ─────────────────────────────────────────


@pytest.fixture()
def base_yaml_file(tmp_path):
    """Write a minimal base librechat.yaml for testing."""
    content = textwrap.dedent("""\
        version: 1.3.5
        mcpServers:
          klai-knowledge:
            type: streamable-http
            url: http://klai-knowledge-mcp:8080/mcp
        modelSpecs:
          prioritize: true
          list:
            - name: klai-primary
              mcpServers:
                - klai-knowledge
              label: Klai AI
              default: true
    """)
    p = tmp_path / "librechat.yaml"
    p.write_text(content)
    return p


class TestGenerateLibrechatYaml:
    """Tests for SPEC-INFRA-001: _generate_librechat_yaml() yaml merge logic."""

    def test_no_extra_servers_returns_base_config(self, base_yaml_file):
        """When extra_mcp_servers is None, output equals the base config."""
        from app.services.provisioning import _generate_librechat_yaml

        result = _generate_librechat_yaml(base_yaml_file, extra_mcp_servers=None)
        parsed = yaml.safe_load(result)

        assert "klai-knowledge" in parsed["mcpServers"]
        assert len(parsed["mcpServers"]) == 1
        assert parsed["modelSpecs"]["list"][0]["mcpServers"] == ["klai-knowledge"]

    def test_extra_servers_merged_into_mcp_section(self, base_yaml_file):
        """Extra MCP servers are added to the mcpServers section."""
        from app.services.provisioning import _generate_librechat_yaml

        extra = {
            "twenty-crm": {
                "type": "stdio",
                "command": "npx",
                "args": ["-y", "twenty-mcp-server", "start"],
                "env": {"TWENTY_API_KEY": "${TWENTY_API_KEY}"},
            }
        }
        result = _generate_librechat_yaml(base_yaml_file, extra_mcp_servers=extra)
        parsed = yaml.safe_load(result)

        assert "klai-knowledge" in parsed["mcpServers"]
        assert "twenty-crm" in parsed["mcpServers"]
        assert parsed["mcpServers"]["twenty-crm"]["type"] == "stdio"

    def test_extra_server_names_added_to_model_specs(self, base_yaml_file):
        """Extra server names are appended to modelSpecs.list[].mcpServers."""
        from app.services.provisioning import _generate_librechat_yaml

        extra = {"twenty-crm": {"type": "stdio", "command": "npx"}}
        result = _generate_librechat_yaml(base_yaml_file, extra_mcp_servers=extra)
        parsed = yaml.safe_load(result)

        spec_servers = parsed["modelSpecs"]["list"][0]["mcpServers"]
        assert spec_servers == ["klai-knowledge", "twenty-crm"]

    def test_base_config_not_mutated(self, base_yaml_file):
        """Calling with extra servers does not modify the base file on disk."""
        from app.services.provisioning import _generate_librechat_yaml

        original = base_yaml_file.read_text()
        _generate_librechat_yaml(base_yaml_file, extra_mcp_servers={"test": {"type": "stdio"}})
        assert base_yaml_file.read_text() == original

    def test_empty_extra_servers_dict_is_noop(self, base_yaml_file):
        """An empty dict for extra_mcp_servers does not change the output."""
        from app.services.provisioning import _generate_librechat_yaml

        result_none = _generate_librechat_yaml(base_yaml_file, extra_mcp_servers=None)
        result_empty = _generate_librechat_yaml(base_yaml_file, extra_mcp_servers={})
        # Empty dict is falsy, so same as None
        assert yaml.safe_load(result_none) == yaml.safe_load(result_empty)
