"""Async Redis connection pool singleton.

# @MX:NOTE: [AUTO] Lazy-init singleton pool for retrieval logs + feedback idempotency. SPEC-KB-015.

Usage:
    from app.services.redis_client import get_redis_pool
    pool = await get_redis_pool()
    if pool:
        await pool.set("key", "value", ex=3600)
"""

from urllib.parse import quote, urlparse, urlunparse

import redis.asyncio as redis
import structlog

from app.core.config import settings

logger = structlog.get_logger()

# Mutable holder so tests can reset the singleton
_pool_holder: dict = {"pool": None}


def _safe_redis_url(url: str) -> str:
    """URL-encode the password in a redis:// URL to handle special characters.

    Passwords generated by `openssl rand -base64 32` contain `/`, `+`, `=`
    which break urllib's URL parser unless percent-encoded first.
    """
    parsed = urlparse(url)
    if parsed.password:
        safe_password = quote(parsed.password, safe="")
        netloc = f":{safe_password}@{parsed.hostname}:{parsed.port}"
        return urlunparse(parsed._replace(netloc=netloc))
    return url


async def get_redis_pool() -> redis.Redis | None:
    """Return the shared async Redis client, or None if redis_url is not configured."""
    if _pool_holder["pool"] is not None:
        return _pool_holder["pool"]

    if not settings.redis_url:
        return None

    _pool_holder["pool"] = redis.from_url(
        _safe_redis_url(settings.redis_url),
        decode_responses=True,
    )
    logger.info("redis_pool_initialized", url=settings.redis_url.split("@")[-1])
    return _pool_holder["pool"]
