/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProvisioningRouteImport } from './routes/provisioning'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoggedOutRouteImport } from './routes/logged-out'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as Setup2faRouteImport } from './routes/setup/2fa'
import { Route as PasswordSetRouteImport } from './routes/password/set'
import { Route as PasswordForgotRouteImport } from './routes/password/forgot'
import { Route as AppTranscribeRouteImport } from './routes/app/transcribe'
import { Route as AppScribeRouteImport } from './routes/app/scribe'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppAccountRouteImport } from './routes/app/account'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminBillingRouteImport } from './routes/admin/billing'
import { Route as LocaleSignupRouteImport } from './routes/$locale/signup'
import { Route as LocalePasswordForgotRouteImport } from './routes/$locale/password/forgot'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvisioningRoute = ProvisioningRouteImport.update({
  id: '/provisioning',
  path: '/provisioning',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggedOutRoute = LoggedOutRouteImport.update({
  id: '/logged-out',
  path: '/logged-out',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Setup2faRoute = Setup2faRouteImport.update({
  id: '/setup/2fa',
  path: '/setup/2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordSetRoute = PasswordSetRouteImport.update({
  id: '/password/set',
  path: '/password/set',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordForgotRoute = PasswordForgotRouteImport.update({
  id: '/password/forgot',
  path: '/password/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTranscribeRoute = AppTranscribeRouteImport.update({
  id: '/transcribe',
  path: '/transcribe',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppScribeRoute = AppScribeRouteImport.update({
  id: '/scribe',
  path: '/scribe',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LocaleSignupRoute = LocaleSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePasswordForgotRoute = LocalePasswordForgotRouteImport.update({
  id: '/password/forgot',
  path: '/password/forgot',
  getParentRoute: () => LocaleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/logged-out': typeof LoggedOutRoute
  '/login': typeof LoginRoute
  '/provisioning': typeof ProvisioningRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/$locale/signup': typeof LocaleSignupRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/account': typeof AppAccountRoute
  '/app/chat': typeof AppChatRoute
  '/app/scribe': typeof AppScribeRoute
  '/app/transcribe': typeof AppTranscribeRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/set': typeof PasswordSetRoute
  '/setup/2fa': typeof Setup2faRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/$locale/password/forgot': typeof LocalePasswordForgotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/logged-out': typeof LoggedOutRoute
  '/login': typeof LoginRoute
  '/provisioning': typeof ProvisioningRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/$locale/signup': typeof LocaleSignupRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/account': typeof AppAccountRoute
  '/app/chat': typeof AppChatRoute
  '/app/scribe': typeof AppScribeRoute
  '/app/transcribe': typeof AppTranscribeRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/set': typeof PasswordSetRoute
  '/setup/2fa': typeof Setup2faRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/$locale/password/forgot': typeof LocalePasswordForgotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/logged-out': typeof LoggedOutRoute
  '/login': typeof LoginRoute
  '/provisioning': typeof ProvisioningRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/$locale/signup': typeof LocaleSignupRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/account': typeof AppAccountRoute
  '/app/chat': typeof AppChatRoute
  '/app/scribe': typeof AppScribeRoute
  '/app/transcribe': typeof AppTranscribeRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/set': typeof PasswordSetRoute
  '/setup/2fa': typeof Setup2faRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/$locale/password/forgot': typeof LocalePasswordForgotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/admin'
    | '/app'
    | '/callback'
    | '/logged-out'
    | '/login'
    | '/provisioning'
    | '/signup'
    | '/verify'
    | '/$locale/signup'
    | '/admin/billing'
    | '/admin/settings'
    | '/admin/users'
    | '/app/account'
    | '/app/chat'
    | '/app/scribe'
    | '/app/transcribe'
    | '/password/forgot'
    | '/password/set'
    | '/setup/2fa'
    | '/admin/'
    | '/app/'
    | '/$locale/password/forgot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/callback'
    | '/logged-out'
    | '/login'
    | '/provisioning'
    | '/signup'
    | '/verify'
    | '/$locale/signup'
    | '/admin/billing'
    | '/admin/settings'
    | '/admin/users'
    | '/app/account'
    | '/app/chat'
    | '/app/scribe'
    | '/app/transcribe'
    | '/password/forgot'
    | '/password/set'
    | '/setup/2fa'
    | '/admin'
    | '/app'
    | '/$locale/password/forgot'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/admin'
    | '/app'
    | '/callback'
    | '/logged-out'
    | '/login'
    | '/provisioning'
    | '/signup'
    | '/verify'
    | '/$locale/signup'
    | '/admin/billing'
    | '/admin/settings'
    | '/admin/users'
    | '/app/account'
    | '/app/chat'
    | '/app/scribe'
    | '/app/transcribe'
    | '/password/forgot'
    | '/password/set'
    | '/setup/2fa'
    | '/admin/'
    | '/app/'
    | '/$locale/password/forgot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LoggedOutRoute: typeof LoggedOutRoute
  LoginRoute: typeof LoginRoute
  ProvisioningRoute: typeof ProvisioningRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
  PasswordForgotRoute: typeof PasswordForgotRoute
  PasswordSetRoute: typeof PasswordSetRoute
  Setup2faRoute: typeof Setup2faRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provisioning': {
      id: '/provisioning'
      path: '/provisioning'
      fullPath: '/provisioning'
      preLoaderRoute: typeof ProvisioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logged-out': {
      id: '/logged-out'
      path: '/logged-out'
      fullPath: '/logged-out'
      preLoaderRoute: typeof LoggedOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/setup/2fa': {
      id: '/setup/2fa'
      path: '/setup/2fa'
      fullPath: '/setup/2fa'
      preLoaderRoute: typeof Setup2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/set': {
      id: '/password/set'
      path: '/password/set'
      fullPath: '/password/set'
      preLoaderRoute: typeof PasswordSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/forgot': {
      id: '/password/forgot'
      path: '/password/forgot'
      fullPath: '/password/forgot'
      preLoaderRoute: typeof PasswordForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transcribe': {
      id: '/app/transcribe'
      path: '/transcribe'
      fullPath: '/app/transcribe'
      preLoaderRoute: typeof AppTranscribeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/scribe': {
      id: '/app/scribe'
      path: '/scribe'
      fullPath: '/app/scribe'
      preLoaderRoute: typeof AppScribeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$locale/signup': {
      id: '/$locale/signup'
      path: '/signup'
      fullPath: '/$locale/signup'
      preLoaderRoute: typeof LocaleSignupRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/password/forgot': {
      id: '/$locale/password/forgot'
      path: '/password/forgot'
      fullPath: '/$locale/password/forgot'
      preLoaderRoute: typeof LocalePasswordForgotRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleSignupRoute: typeof LocaleSignupRoute
  LocalePasswordForgotRoute: typeof LocalePasswordForgotRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleSignupRoute: LocaleSignupRoute,
  LocalePasswordForgotRoute: LocalePasswordForgotRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminBillingRoute: typeof AdminBillingRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBillingRoute: AdminBillingRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppChatRoute: typeof AppChatRoute
  AppScribeRoute: typeof AppScribeRoute
  AppTranscribeRoute: typeof AppTranscribeRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppChatRoute: AppChatRoute,
  AppScribeRoute: AppScribeRoute,
  AppTranscribeRoute: AppTranscribeRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoggedOutRoute: LoggedOutRoute,
  LoginRoute: LoginRoute,
  ProvisioningRoute: ProvisioningRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
  PasswordForgotRoute: PasswordForgotRoute,
  PasswordSetRoute: PasswordSetRoute,
  Setup2faRoute: Setup2faRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
