"""create portal_orgs and portal_users

Revision ID: d64fdcfecf32
Revises:
Create Date: 2026-03-07 15:05:26.475637

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d64fdcfecf32"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portal_orgs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zitadel_org_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_portal_orgs_zitadel_org_id"), "portal_orgs", ["zitadel_org_id"], unique=True)
    op.create_table(
        "portal_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zitadel_user_id", sa.String(length=64), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["portal_orgs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_portal_users_email"), "portal_users", ["email"], unique=False)
    op.create_index(op.f("ix_portal_users_zitadel_user_id"), "portal_users", ["zitadel_user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_portal_users_zitadel_user_id"), table_name="portal_users")
    op.drop_index(op.f("ix_portal_users_email"), table_name="portal_users")
    op.drop_table("portal_users")
    op.drop_index(op.f("ix_portal_orgs_zitadel_org_id"), table_name="portal_orgs")
    op.drop_table("portal_orgs")
    # ### end Alembic commands ###
